[package]
name = "client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
shared.workspace = true
server = { path = "../server" }
bevy = { workspace = true, features = ["3d", "ui", "audio", "wav", "tonemapping_luts"] }
bevy_hanabi.workspace = true
anyhow.workspace = true
serde.workspace = true

[lints]
workspace = true
